E
======================================================================
ERROR: Failure: OSError (No such file /home/yikong/workspace/apt_lab3/2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /home/yikong/workspace/apt_lab3/2

Name                    Stmts   Miss  Cover   Missing
-----------------------------------------------------
Experiment                 10      1    90%   12
Experiment-Test            20      0   100%   
experiment/Experiment   NoSource: No source for code: '/home/yikong/workspace/apt_lab3/experiment/Experiment.py'
experiment/__init__   NoSource: No source for code: '/home/yikong/workspace/apt_lab3/experiment/__init__.py'
tests/ExperimentTest   NoSource: No source for code: '/home/yikong/workspace/apt_lab3/tests/ExperimentTest.py'
tests/__init__   NoSource: No source for code: '/home/yikong/workspace/apt_lab3/tests/__init__.py'
-----------------------------------------------------
TOTAL                      30      1    97%   
----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
