....F
======================================================================
FAIL: test_t5 (Experiment-Test.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yikong/workspace/apt_lab3/Experiment-Test.py", line 24, in test_t5
    self.assertEqual(r1, -1)
AssertionError: 0 != -1

Name         Stmts   Miss  Cover   Missing
------------------------------------------
Experiment      10      2    80%   5, 12
----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=1)
